{
	"numberPotMeters": ~numberPotMeters~,
	"throttleSubType": ~throttleSubType~,
	"minimumLevel": ~minimumLevel~,
	"minimumLevel2": ~minimumLevel2~,
	"maximumLevel": ~maximumLevel~,
	"maximumLevel2": ~maximumLevel2~,
	"positionRegenMaximum": ~positionRegenMaximum~,
	"positionRegenMinimum": ~positionRegenMinimum~,
	"positionForwardStart": ~positionForwardStart~,
	"positionHalfPower": ~positionHalfPower~,
	"minimumRegen": ~minimumRegen~,
	"maximumRegen": ~maximumRegen~,
	"creep": ~creep~,
	"brakeMinimumLevel": ~brakeMinimumLevel~,
	"brakeMaximumLevel": ~brakeMaximumLevel~,
	"brakeMinimumRegen": ~brakeMinimumRegen~,
	"brakeMaximumRegen": ~brakeMaximumRegen~,

	"speedMax": ~speedMax~,
	"torqueMax": ~torqueMax~,
	"motorMode": ~motorMode~,
	"nominalVolt": ~nominalVolt~,
	"invertDirection": ~invertDirection~,
	"slewRate": ~slewRate~,
	"slewType": ~slewType~,

	"maxMechPowerMotor": ~maxMechPowerMotor~,
	"maxMechPowerRegen": ~maxMechPowerRegen~,
	"dcVoltLimitMotor": ~dcVoltLimitMotor~,
	"dcVoltLimitRegen": ~dcVoltLimitRegen~,
	"dcCurrentLimitMotor": ~dcCurrentLimitMotor~,
	"dcCurrentLimitRegen": ~dcCurrentLimitRegen~,
	"enableOscLimiter": ~enableOscLimiter~,

	"device_x1000": ~x1000~,
	"device_x1001": ~x1001~,
	"device_x1002": ~x1002~,
	"device_x1031": ~x1031~,
	"device_x1032": ~x1032~,
	"device_x1033": ~x1033~,
	"device_x1034": ~x1034~
}
